### ISSUE TITLE
Proxy authentication method configuration support

### ISSUE THREAD

**Issue by slavb18** [yast/yast-proxy#11]
Hi!

Curl poxy authentication is defaulted to --proxy-basic, while there is other methods avaiiable

 --proxy-anyauth
              Tells curl to pick a suitable authentication method when communicating with the given proxy. This might cause an extra request/response round-trip. (Added in 7.13.2)

```
   --proxy-basic
          Tells  curl  to use HTTP Basic authentication when communicating with the given proxy. Use --basic for enabling HTTP Basic with a remote host. Basic is the default authentication method curl
          uses with proxies.

   --proxy-digest
          Tells curl to use HTTP Digest authentication when communicating with the given proxy. Use --digest for enabling HTTP Digest with a remote host.

   --proxy-negotiate
          Tells curl to use HTTP Negotiate authentication when communicating with the given proxy. Use --negotiate for enabling HTTP Negotiate with a remote host. (Added in 7.17.1)

   --proxy-ntlm
          Tells curl to use HTTP NTLM authentication when communicating with the given proxy. Use --ntlm for enabling NTLM with a remote host.
```

Currently yast-proxy  does no allows to select proxy authentication method, and e.g. with digest proxy auth generated .curlrc is not working (getting curl: (56) Received HTTP code 407 from proxy after CONNECT
)

**Comment by dgdavid** [comment]
Hi guys!

As part as an issues cleanup, I'm closing old issues like this (reported 4 years ago).

Please, forgive us for overlooking it during such time and reopen the ticket if you can reproduce the issue yet.

As a side note, don't forget that you can also reach us in the freeenode #yast channel and send bug reports through [Bugzilla](https://bugzilla.suse.com/enter_bug.cgi?format=guided&product=openSUSE+Tumbleweed&component=YaST2), which still being our preferred tool to manage them. See https://yast.opensuse.org/contact

Thanks for the collaboration and understanding.
