### ISSUE TITLE
To add SOCK4|5 proxy parameters

### ISSUE THREAD

**Issue by MikhailKasimov** [yast/yast-proxy#13]
Hello!

The idea is not unique, but is inspired by ```Firefox``` native proxy settings window, which has such field by default -- ```address:port```.

Additional options to be good to have here:
1) sites, CIDRs exclude-list.

2) sites, CIDRs include-list.

SOCK4|5 switcher is radio-button.

Something like this:

![socks5_settings_for_yast](https://cloud.githubusercontent.com/assets/7167300/26755076/d313f2ac-488e-11e7-84aa-c0c48e6a63b4.jpg)

```Real story as the reason to have this```: A couple of days ago my ISP changed some settings on his side and some IPs, including mine, went to ban-list, but connection via SOCK5 was fine. But I couldn't get system updates via ```zypper```. So, having such setting for ```zypper``` seems to be right idea: user sets his socks4|5 proxy connection via ```yast-proxy``` module and can have up-to-dated system.

Of course, now everything is OK, ISP has fixed his bug and I can have my direct Internet connection again.

Thanks!

**Comment by dgdavid** [comment]
Hi @MikhailKasimov 

First of all, thank you so much for the input. Although we overlooked it, it's much appreciated.

As said in a recent closed issue, 

>
> 
> As part as an issues cleanup, I'm closing old issues like this.
>
> Please, forgive us for overlooking it during such time and reopen the ticket if you can reproduce the issue yet.
> 
> As a side note, don't forget that you can also reach us in the freenode #yast channel and send bug reports also through [Bugzilla](https://bugzilla.suse.com/enter_bug.cgi?format=guided&product=openSUSE+Tumbleweed&component=YaST2), which still being our preferred tool to manage them. See https://yast.opensuse.org/contact
> 
> **Thanks for the collaboration and understanding**.

**Comment by MikhailKasimov** [comment]
Hello, @dgdavid ! 

I think, there was no reason to close issue, because it is not a problem\bug, which claims to be reproduced, but feature request instead. So, if described feature applicable\doable is, please, reopen current issue.

Thank you!

**Comment by dgdavid** [comment]
So, you still interested in the described feature, isn't it?

**Comment by MikhailKasimov** [comment]
> So, you still interested in the described feature, isn't it?

Yes.

**Comment by dgdavid** [comment]
Then, let's see if we could address it.

Thanks!

**Comment by dgdavid** [comment]
@MikhailKasimov 

After discuss it with the team, seems that requesting openSUSE features should be done via Bugzilla now that fate.opensuse.org is no longer available. As simple as reporting a bug report marked as enhancement.

I'll transfer this, but for future requests would be better to report the bug directly.

Thanks.

**Comment by dgdavid** [comment]
Here you have it

https://bugzilla.opensuse.org/show_bug.cgi?id=1163088

Please, feel free to add more information or clarify whatever you need there.

I'm closing this issue in favor of the bug report.

Thank you!
