### ISSUE TITLE
NO_PROXY settings are not written to .curlrc

### ISSUE THREAD

**Issue by rakuco** [yast/yast-proxy#2]
yast-proxy does not add a corresponding `--noproxy` to `.curlrc` even when it has an actual value.

This means that if certain Zypper repositories depend on proxies while others depend on the _absence_ of proxies, connecting to some of them will fail.

**Comment by cwh42** [comment]
There is a rspec test which indicates that this issue is already fixed. Is that right, @mvidner ?

  Yast::ProxyClass
    #WriteCurlrc
      deletes proxy entries, when proxy is disabled
      writes proxy settings, and a comment, when proxy is enabled
      writes proxy settings, and a comment, when proxy is enabled via InstallInfConvertor
      writes a no-proxy setting
      writes a no-proxy setting without spaces
      escapes user name
