### ISSUE TITLE
Please add corporate proxy support

### ISSUE THREAD

**Issue by sharique** [yast/yast-proxy#5]
I'm running OpenSuse Vm behind Corporate firewall, which has multiple proxy servers. I tried configuring it in OpenSuse 13.2 but it does not works.

**Comment by dgdavid** [comment]
Hi!

Since I'm not sure if this issue still relevant nowadays (it was opened more than 5 years ago), I'm going to close it.

Please, reopen it if you can reproduce the problem yet and provide enough information to address it.

Thanks for understanding.
